apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pvqf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0010-tenant/tkrw-pr712-0075-0010-app/devfile-sample-pvqf@sha256:bb4a6ab0d4793675d757d5d256da495f1e4395315534daad6b3f445367e31afd
        name: my-nodejs
        resources: {}
status: {}
